<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = [
            ['iso' => 'US','iso3'=>'US','nicename'=> 'United States','name' => 'United States', 'available' => 0],
            ['iso' => 'CA','iso3'=>'CA','nicename'=> 'Canada','name' => 'Canada', 'available' => 0],
            ['iso' => 'AF','iso3'=>'AF','nicename'=> 'Afghanistan','name' => 'Afghanistan', 'available' => 0],
            ['iso' => 'AL','iso3'=>'AL','nicename'=> 'Albania','name' => 'Albania', 'available' => 0],
            ['iso' => 'DZ','iso3'=>'DZ','nicename'=> 'Algeria','name' => 'Algeria', 'available' => 0],
            ['iso' => 'AS','iso3'=>'AS','nicename'=> 'American Samoa','name' => 'American Samoa', 'available' => 0],
            ['iso' => 'AD','iso3'=>'AD','nicename'=> 'Andorra','name' => 'Andorra', 'available' => 0],
            ['iso' => 'AO','iso3'=>'AO','nicename'=> 'Angola','name' => 'Angola', 'available' => 0],
            ['iso' => 'AI','iso3'=>'AI','nicename'=> 'Anguilla','name' => 'Anguilla', 'available' => 0],
            ['iso' => 'AQ','iso3'=>'AQ','nicename'=> 'Antarctica','name' => 'Antarctica', 'available' => 0],
            ['iso' => 'AG','iso3'=>'AG','nicename'=> 'Antigua and/or Barbuda','name' => 'Antigua and/or Barbuda', 'available' => 0],
            ['iso' => 'AR','iso3'=>'AR','nicename'=> 'Argentina','name' => 'Argentina', 'available' => 0],
            ['iso' => 'AM','iso3'=>'AM','nicename'=> 'Armenia','name' => 'Armenia', 'available' => 0],
            ['iso' => 'AW','iso3'=>'AW','nicename'=> 'Aruba','name' => 'Aruba', 'available' => 0],
            ['iso' => 'AU','iso3'=>'AU','nicename'=> 'Australia','name' => 'Australia', 'available' => 0],
            ['iso' => 'AT','iso3'=>'AT','nicename'=> 'Austria','name' => 'Austria', 'available' => 0],
            ['iso' => 'AZ','iso3'=>'AZ','nicename'=> 'Azerbaijan','name' => 'Azerbaijan', 'available' => 0],
            ['iso' => 'BS','iso3'=>'BS','nicename'=> 'Bahamas','name' => 'Bahamas', 'available' => 0],
            ['iso' => 'BH','iso3'=>'BH','nicename'=> 'Bahrain','name' => 'Bahrain', 'available' => 0],
            ['iso' => 'BD','iso3'=>'BD','nicename'=> 'Bangladesh','name' => 'Bangladesh', 'available' => 0],
            ['iso' => 'BB','iso3'=>'BB','nicename'=> 'Barbados','name' => 'Barbados', 'available' => 0],
            ['iso' => 'BY','iso3'=>'BY','nicename'=> 'Belarus','name' => 'Belarus', 'available' => 0],
            ['iso' => 'BE','iso3'=>'BE','nicename'=> 'Belgium','name' => 'Belgium', 'available' => 0],
            ['iso' => 'BZ','iso3'=>'BZ','nicename'=> 'Belize','name' => 'Belize', 'available' => 0],
            ['iso' => 'BJ','iso3'=>'BJ','nicename'=> 'Benin','name' => 'Benin', 'available' => 0],
            ['iso' => 'BM','iso3'=>'BM','nicename'=> 'Bermuda','name' => 'Bermuda', 'available' => 0],
            ['iso' => 'BT','iso3'=>'BT','nicename'=> 'Bhutan','name' => 'Bhutan', 'available' => 0],
            ['iso' => 'BO','iso3'=>'BO','nicename'=> 'Bolivia','name' => 'Bolivia', 'available' => 0],
            ['iso' => 'BA','iso3'=>'BA','nicename'=> 'Bosnia and Herzegovina','name' => 'Bosnia and Herzegovina', 'available' => 0],
            ['iso' => 'BW','iso3'=>'BW','nicename'=> 'Botswana','name' => 'Botswana', 'available' => 0],
            ['iso' => 'BV','iso3'=>'BV','nicename'=> 'Bouvet Island','name' => 'Bouvet Island', 'available' => 0],
            ['iso' => 'BR','iso3'=>'BR','nicename'=> 'Brazil','name' => 'Brazil', 'available' => 0],
            ['iso' => 'IO','iso3'=>'IO','nicename'=> 'British lndian Ocean Territory','name' => 'British lndian Ocean Territory', 'available' => 0],
            ['iso' => 'BN','iso3'=>'BN','nicename'=> 'Brunei Darussalam','name' => 'Brunei Darussalam', 'available' => 0],
            ['iso' => 'BG','iso3'=>'BG','nicename'=> 'Bulgaria','name' => 'Bulgaria', 'available' => 0],
            ['iso' => 'BF','iso3'=>'BF','nicename'=> 'Burkina Faso','name' => 'Burkina Faso', 'available' => 0],
            ['iso' => 'BI','iso3'=>'BI','nicename'=> 'Burundi','name' => 'Burundi', 'available' => 0],
            ['iso' => 'KH','iso3'=>'KH','nicename'=> 'Cambodia','name' => 'Cambodia', 'available' => 0],
            ['iso' => 'CM','iso3'=>'CM','nicename'=> 'Cameroon','name' => 'Cameroon', 'available' => 0],
            ['iso' => 'CV','iso3'=>'CV','nicename'=> 'Cape Verde','name' => 'Cape Verde', 'available' => 0],
            ['iso' => 'KY','iso3'=>'KY','nicename'=> 'Cayman Islands','name' => 'Cayman Islands', 'available' => 0],
            ['iso' => 'CF','iso3'=>'CF','nicename'=> 'Central African Republic','name' => 'Central African Republic', 'available' => 0],
            ['iso' => 'TD','iso3'=>'TD','nicename'=> 'Chad','name' => 'Chad', 'available' => 0],
            ['iso' => 'CL','iso3'=>'CL','nicename'=> 'Chile','name' => 'Chile', 'available' => 0],
            ['iso' => 'CN','iso3'=>'CN','nicename'=> 'China','name' => 'China', 'available' => 0],
            ['iso' => 'CX','iso3'=>'CX','nicename'=> 'Christmas Island','name' => 'Christmas Island', 'available' => 0],
            ['iso' => 'CC','iso3'=>'CC','nicename'=> 'Cocos (Keeling) Islands','name' => 'Cocos (Keeling) Islands', 'available' => 0],
            ['iso' => 'CO','iso3'=>'CO','nicename'=> 'Colombia','name' => 'Colombia', 'available' => 0],
            ['iso' => 'KM','iso3'=>'KM','nicename'=> 'Comoros','name' => 'Comoros', 'available' => 0],
            ['iso' => 'CG','iso3'=>'CG','nicename'=> 'Congo','name' => 'Congo', 'available' => 0],
            ['iso' => 'CK','iso3'=>'CK','nicename'=> 'Cook Islands','name' => 'Cook Islands', 'available' => 0],
            ['iso' => 'CR','iso3'=>'CR','nicename'=> 'Costa Rica','name' => 'Costa Rica', 'available' => 0],
            ['iso' => 'HR','iso3'=>'HR','nicename'=> 'Croatia (Hrvatska)','name' => 'Croatia (Hrvatska)', 'available' => 0],
            ['iso' => 'CU','iso3'=>'CU','nicename'=> 'Cuba','name' => 'Cuba', 'available' => 0],
            ['iso' => 'CY','iso3'=>'CY','nicename'=> 'Cyprus','name' => 'Cyprus', 'available' => 0],
            ['iso' => 'CZ','iso3'=>'CZ','nicename'=> 'Czech Republic','name' => 'Czech Republic', 'available' => 0],
            ['iso' => 'CD','iso3'=>'CD','nicename'=> 'Democratic Republic of Congo','name' => 'Democratic Republic of Congo', 'available' => 0],
            ['iso' => 'DK','iso3'=>'DK','nicename'=> 'Denmark','name' => 'Denmark', 'available' => 0],
            ['iso' => 'DJ','iso3'=>'DJ','nicename'=> 'Djibouti','name' => 'Djibouti', 'available' => 0],
            ['iso' => 'DM','iso3'=>'DM','nicename'=> 'Dominica','name' => 'Dominica', 'available' => 0],
            ['iso' => 'DO','iso3'=>'DO','nicename'=> 'Dominican Republic','name' => 'Dominican Republic', 'available' => 0],
            ['iso' => 'TP','iso3'=>'TP','nicename'=> 'East Timor','name' => 'East Timor', 'available' => 0],
            ['iso' => 'EC','iso3'=>'EC','nicename'=> 'Ecudaor','name' => 'Ecudaor', 'available' => 0],
            ['iso' => 'EG','iso3'=>'EG','nicename'=> 'Egypt','name' => 'Egypt', 'available' => 0],
            ['iso' => 'SV','iso3'=>'SV','nicename'=> 'El Salvador','name' => 'El Salvador', 'available' => 0],
            ['iso' => 'GQ','iso3'=>'GQ','nicename'=> 'Equatorial Guinea','name' => 'Equatorial Guinea', 'available' => 0],
            ['iso' => 'ER','iso3'=>'ER','nicename'=> 'Eritrea','name' => 'Eritrea', 'available' => 0],
            ['iso' => 'EE','iso3'=>'EE','nicename'=> 'Estonia','name' => 'Estonia', 'available' => 0],
            ['iso' => 'ET','iso3'=>'ET','nicename'=> 'Ethiopia','name' => 'Ethiopia', 'available' => 0],
            ['iso' => 'FK','iso3'=>'FK','nicename'=> 'Falkland Islands (Malvinas)','name' => 'Falkland Islands (Malvinas)', 'available' => 0],
            ['iso' => 'FO','iso3'=>'FO','nicename'=> 'Faroe Islands','name' => 'Faroe Islands', 'available' => 0],
            ['iso' => 'FJ','iso3'=>'FJ','nicename'=> 'Fiji','name' => 'Fiji', 'available' => 0],
            ['iso' => 'FI','iso3'=>'FI','nicename'=> 'Finland','name' => 'Finland', 'available' => 0],
            ['iso' => 'FR','iso3'=>'FR','nicename'=> 'France','name' => 'France', 'available' => 0],
            ['iso' => 'FX','iso3'=>'FX','nicename'=> 'France, Metropolitan','name' => 'France, Metropolitan', 'available' => 0],
            ['iso' => 'GF','iso3'=>'GF','nicename'=> 'French Guiana','name' => 'French Guiana', 'available' => 0],
            ['iso' => 'PF','iso3'=>'PF','nicename'=> 'French Polynesia','name' => 'French Polynesia', 'available' => 0],
            ['iso' => 'TF','iso3'=>'TF','nicename'=> 'French Southern Territories','name' => 'French Southern Territories', 'available' => 0],
            ['iso' => 'GA','iso3'=>'GA','nicename'=> 'Gabon','name' => 'Gabon', 'available' => 0],
            ['iso' => 'GM','iso3'=>'GM','nicename'=> 'Gambia','name' => 'Gambia', 'available' => 0],
            ['iso' => 'GE','iso3'=>'GE','nicename'=> 'Georgia','name' => 'Georgia', 'available' => 0],
            ['iso' => 'DE','iso3'=>'DE','nicename'=> 'Germany','name' => 'Germany', 'available' => 0],
            ['iso' => 'GH','iso3'=>'GH','nicename'=> 'Ghana','name' => 'Ghana', 'available' => 0],
            ['iso' => 'GI','iso3'=>'GI','nicename'=> 'Gibraltar','name' => 'Gibraltar', 'available' => 0],
            ['iso' => 'GR','iso3'=>'GR','nicename'=> 'Greece','name' => 'Greece', 'available' => 0],
            ['iso' => 'GL','iso3'=>'GL','nicename'=> 'Greenland','name' => 'Greenland', 'available' => 0],
            ['iso' => 'GD','iso3'=>'GD','nicename'=> 'Grenada','name' => 'Grenada', 'available' => 0],
            ['iso' => 'GP','iso3'=>'GP','nicename'=> 'Guadeloupe','name' => 'Guadeloupe', 'available' => 0],
            ['iso' => 'GU','iso3'=>'GU','nicename'=> 'Guam','name' => 'Guam', 'available' => 0],
            ['iso' => 'GT','iso3'=>'GT','nicename'=> 'Guatemala','name' => 'Guatemala', 'available' => 0],
            ['iso' => 'GN','iso3'=>'GN','nicename'=> 'Guinea','name' => 'Guinea', 'available' => 0],
            ['iso' => 'GW','iso3'=>'GW','nicename'=> 'Guinea-Bissau','name' => 'Guinea-Bissau', 'available' => 0],
            ['iso' => 'GY','iso3'=>'GY','nicename'=> 'Guyana','name' => 'Guyana', 'available' => 0],
            ['iso' => 'HT','iso3'=>'HT','nicename'=> 'Haiti','name' => 'Haiti', 'available' => 0],
            ['iso' => 'HM','iso3'=>'HM','nicename'=> 'Heard and Mc Donald Islands','name' => 'Heard and Mc Donald Islands', 'available' => 0],
            ['iso' => 'HN','iso3'=>'HN','nicename'=> 'Honduras','name' => 'Honduras', 'available' => 0],
            ['iso' => 'HK','iso3'=>'HK','nicename'=> 'Hong Kong','name' => 'Hong Kong', 'available' => 0],
            ['iso' => 'HU','iso3'=>'HU','nicename'=> 'Hungary','name' => 'Hungary', 'available' => 0],
            ['iso' => 'IS','iso3'=>'IS','nicename'=> 'Iceland','name' => 'Iceland', 'available' => 0],
            ['iso' => 'IN','iso3'=>'IN','nicename'=> 'India','name' => 'India', 'available' => 0],
            ['iso' => 'ID','iso3'=>'ID','nicename'=> 'Indonesia','name' => 'Indonesia', 'available' => 0],
            ['iso' => 'IR','iso3'=>'IR','nicename'=> 'Iran (Islamic Republic of)','name' => 'Iran (Islamic Republic of)', 'available' => 0],
            ['iso' => 'IQ','iso3'=>'IQ','nicename'=> 'Iraq','name' => 'Iraq', 'available' => 0],
            ['iso' => 'IE','iso3'=>'IE','nicename'=> 'Ireland','name' => 'Ireland', 'available' => 0],
            ['iso' => 'IL','iso3'=>'IL','nicename'=> 'Israel','name' => 'Israel', 'available' => 0],
            ['iso' => 'IT','iso3'=>'IT','nicename'=> 'Italy','name' => 'Italy', 'available' => 0],
            ['iso' => 'CI','iso3'=>'CI','nicename'=> 'Ivory Coast','name' => 'Ivory Coast', 'available' => 0],
            ['iso' => 'JM','iso3'=>'JM','nicename'=> 'Jamaica','name' => 'Jamaica', 'available' => 0],
            ['iso' => 'JP','iso3'=>'JP','nicename'=> 'Japan','name' => 'Japan', 'available' => 0],
            ['iso' => 'JO','iso3'=>'JO','nicename'=> 'Jordan','name' => 'Jordan', 'available' => 0],
            ['iso' => 'KZ','iso3'=>'KZ','nicename'=> 'Kazakhstan','name' => 'Kazakhstan', 'available' => 0],
            ['iso' => 'KE','iso3'=>'KE','nicename'=> 'Kenya','name' => 'Kenya', 'available' => 0],
            ['iso' => 'KI','iso3'=>'KI','nicename'=> 'Kiribati','name' => 'Kiribati', 'available' => 0],
            ['iso' => 'KP','iso3'=>'KP','nicename'=> 'Korea, Democratic People\'s Republ','name' => 'Korea, Democratic People\'s Republic of', 'available' => 0],
            ['iso' => 'KR','iso3'=>'KR','nicename'=> 'Korea, Republic of','name' => 'Korea, Republic of', 'available' => 0],
            ['iso' => 'KW','iso3'=>'KW','nicename'=> 'Kuwait','name' => 'Kuwait', 'available' => 0],
            ['iso' => 'KG','iso3'=>'KG','nicename'=> 'Kyrgyzstan','name' => 'Kyrgyzstan', 'available' => 0],
            ['iso' => 'LA','iso3'=>'LA','nicename'=> 'Lao People\'s Democratic Republic','name' => 'Lao People\'s Democratic Republic', 'available' => 0],
            ['iso' => 'LV','iso3'=>'LV','nicename'=> 'Latvia','name' => 'Latvia', 'available' => 0],
            ['iso' => 'LB','iso3'=>'LB','nicename'=> 'Lebanon','name' => 'Lebanon', 'available' => 0],
            ['iso' => 'LS','iso3'=>'LS','nicename'=> 'Lesotho','name' => 'Lesotho', 'available' => 0],
            ['iso' => 'LR','iso3'=>'LR','nicename'=> 'Liberia','name' => 'Liberia', 'available' => 0],
            ['iso' => 'LY','iso3'=>'LY','nicename'=> 'Libyan Arab Jamahiriya','name' => 'Libyan Arab Jamahiriya', 'available' => 0],
            ['iso' => 'LI','iso3'=>'LI','nicename'=> 'Liechtenstein','name' => 'Liechtenstein', 'available' => 0],
            ['iso' => 'LT','iso3'=>'LT','nicename'=> 'Lithuania','name' => 'Lithuania', 'available' => 0],
            ['iso' => 'LU','iso3'=>'LU','nicename'=> 'Luxembourg','name' => 'Luxembourg', 'available' => 0],
            ['iso' => 'MO','iso3'=>'MO','nicename'=> 'Macau','name' => 'Macau', 'available' => 0],
            ['iso' => 'MK','iso3'=>'MK','nicename'=> 'Macedonia','name' => 'Macedonia', 'available' => 0],
            ['iso' => 'MG','iso3'=>'MG','nicename'=> 'Madagascar','name' => 'Madagascar', 'available' => 0],
            ['iso' => 'MW','iso3'=>'MW','nicename'=> 'Malawi','name' => 'Malawi', 'available' => 0],
            ['iso' => 'MY','iso3'=>'MY','nicename'=> 'Malaysia','name' => 'Malaysia', 'available' => 0],
            ['iso' => 'MV','iso3'=>'MV','nicename'=> 'Maldives','name' => 'Maldives', 'available' => 0],
            ['iso' => 'ML','iso3'=>'ML','nicename'=> 'Mali','name' => 'Mali', 'available' => 0],
            ['iso' => 'MT','iso3'=>'MT','nicename'=> 'Malta','name' => 'Malta', 'available' => 0],
            ['iso' => 'MH','iso3'=>'MH','nicename'=> 'Marshall Islands','name' => 'Marshall Islands', 'available' => 0],
            ['iso' => 'MQ','iso3'=>'MQ','nicename'=> 'Martinique','name' => 'Martinique', 'available' => 0],
            ['iso' => 'MR','iso3'=>'MR','nicename'=> 'Mauritania','name' => 'Mauritania', 'available' => 0],
            ['iso' => 'MU','iso3'=>'MU','nicename'=> 'Mauritius','name' => 'Mauritius', 'available' => 0],
            ['iso' => 'TY','iso3'=>'TY','nicename'=> 'Mayotte','name' => 'Mayotte', 'available' => 0],
            ['iso' => 'MX','iso3'=>'MX','nicename'=> 'Mexico','name' => 'Mexico', 'available' => 0],
            ['iso' => 'FM','iso3'=>'FM','nicename'=> 'Micronesia, Federated States of','name' => 'Micronesia, Federated States of', 'available' => 0],
            ['iso' => 'MD','iso3'=>'MD','nicename'=> 'Moldova, Republic of','name' => 'Moldova, Republic of', 'available' => 0],
            ['iso' => 'MC','iso3'=>'MC','nicename'=> 'Monaco','name' => 'Monaco', 'available' => 0],
            ['iso' => 'MN','iso3'=>'MN','nicename'=> 'Mongolia','name' => 'Mongolia', 'available' => 0],
            ['iso' => 'MS','iso3'=>'MS','nicename'=> 'Montserrat','name' => 'Montserrat', 'available' => 0],
            ['iso' => 'MA','iso3'=>'MA','nicename'=> 'Morocco','name' => 'Morocco', 'available' => 0],
            ['iso' => 'MZ','iso3'=>'MZ','nicename'=> 'Mozambique','name' => 'Mozambique', 'available' => 0],
            ['iso' => 'MM','iso3'=>'MM','nicename'=> 'Myanmar','name' => 'Myanmar', 'available' => 0],
            ['iso' => 'NA','iso3'=>'NA','nicename'=> 'Namibia','name' => 'Namibia', 'available' => 0],
            ['iso' => 'NR','iso3'=>'NR','nicename'=> 'Nauru','name' => 'Nauru', 'available' => 0],
            ['iso' => 'NP','iso3'=>'NP','nicename'=> 'Nepal','name' => 'Nepal', 'available' => 0],
            ['iso' => 'NL','iso3'=>'NL','nicename'=> 'Netherlands','name' => 'Netherlands', 'available' => 0],
            ['iso' => 'AN','iso3'=>'AN','nicename'=> 'Netherlands Antilles','name' => 'Netherlands Antilles', 'available' => 0],
            ['iso' => 'NC','iso3'=>'NC','nicename'=> 'New Caledonia','name' => 'New Caledonia', 'available' => 0],
            ['iso' => 'NZ','iso3'=>'NZ','nicename'=> 'New Zealand','name' => 'New Zealand', 'available' => 0],
            ['iso' => 'NI','iso3'=>'NI','nicename'=> 'Nicaragua','name' => 'Nicaragua', 'available' => 0],
            ['iso' => 'NE','iso3'=>'NE','nicename'=> 'Niger','name' => 'Niger', 'available' => 0],
            ['iso' => 'NG','iso3'=>'NG','nicename'=> 'Nigeria','name' => 'Nigeria', 'available' => 0],
            ['iso' => 'NU','iso3'=>'NU','nicename'=> 'Niue','name' => 'Niue', 'available' => 0],
            ['iso' => 'NF','iso3'=>'NF','nicename'=> 'Norfork Island','name' => 'Norfork Island', 'available' => 0],
            ['iso' => 'MP','iso3'=>'MP','nicename'=> 'Northern Mariana Islands','name' => 'Northern Mariana Islands', 'available' => 0],
            ['iso' => 'NO','iso3'=>'NO','nicename'=> 'Norway','name' => 'Norway', 'available' => 0],
            ['iso' => 'OM','iso3'=>'OM','nicename'=> 'Oman','name' => 'Oman', 'available' => 0],
            ['iso' => 'PK','iso3'=>'PK','nicename'=> 'Pakistan','name' => 'Pakistan', 'available' => 0],
            ['iso' => 'PW','iso3'=>'PW','nicename'=> 'Palau','name' => 'Palau', 'available' => 0],
            ['iso' => 'PA','iso3'=>'PA','nicename'=> 'Panama','name' => 'Panama', 'available' => 0],
            ['iso' => 'PG','iso3'=>'PG','nicename'=> 'Papua New Guinea','name' => 'Papua New Guinea', 'available' => 0],
            ['iso' => 'PY','iso3'=>'PY','nicename'=> 'Paraguay','name' => 'Paraguay', 'available' => 0],
            ['iso' => 'PE','iso3'=>'PE','nicename'=> 'Peru','name' => 'Peru', 'available' => 0],
            ['iso' => 'PH','iso3'=>'PH','nicename'=> 'Philippines','name' => 'Philippines', 'available' => 0],
            ['iso' => 'PN','iso3'=>'PN','nicename'=> 'Pitcairn','name' => 'Pitcairn', 'available' => 0],
            ['iso' => 'PL','iso3'=>'PL','nicename'=> 'Poland','name' => 'Poland', 'available' => 0],
            ['iso' => 'PT','iso3'=>'PT','nicename'=> 'Portugal','name' => 'Portugal', 'available' => 0],
            ['iso' => 'PR','iso3'=>'PR','nicename'=> 'Puerto Rico','name' => 'Puerto Rico', 'available' => 0],
            ['iso' => 'QA','iso3'=>'QA','nicename'=> 'Qatar','name' => 'Qatar', 'available' => 0],
            ['iso' => 'SS','iso3'=>'SS','nicename'=> 'Republic of South Sudan','name' => 'Republic of South Sudan', 'available' => 0],
            ['iso' => 'RE','iso3'=>'RE','nicename'=> 'Reunion','name' => 'Reunion', 'available' => 0],
            ['iso' => 'RO','iso3'=>'RO','nicename'=> 'Romania','name' => 'Romania', 'available' => 0],
            ['iso' => 'RU','iso3'=>'RU','nicename'=> 'Russian Federation','name' => 'Russian Federation', 'available' => 0],
            ['iso' => 'RW','iso3'=>'RW','nicename'=> 'Rwanda','name' => 'Rwanda', 'available' => 0],
            ['iso' => 'KN','iso3'=>'KN','nicename'=> 'Saint Kitts and Nevis','name' => 'Saint Kitts and Nevis', 'available' => 0],
            ['iso' => 'LC','iso3'=>'LC','nicename'=> 'Saint Lucia','name' => 'Saint Lucia', 'available' => 0],
            ['iso' => 'VC','iso3'=>'VC','nicename'=> 'Saint Vincent and the Grenadines','name' => 'Saint Vincent and the Grenadines', 'available' => 0],
            ['iso' => 'WS','iso3'=>'WS','nicename'=> 'Samoa','name' => 'Samoa', 'available' => 0],
            ['iso' => 'SM','iso3'=>'SM','nicename'=> 'San Marino','name' => 'San Marino', 'available' => 0],
            ['iso' => 'ST','iso3'=>'ST','nicename'=> 'Sao Tome and Principe','name' => 'Sao Tome and Principe', 'available' => 0],
            ['iso' => 'SA','iso3'=>'SA','nicename'=> 'Saudi Arabia','name' => 'Saudi Arabia', 'available' => 0],
            ['iso' => 'SN','iso3'=>'SN','nicename'=> 'Sénégal','name' => 'Sénégal', 'available' => 1],
            ['iso' => 'RS','iso3'=>'RS','nicename'=> 'Serbia','name' => 'Serbia', 'available' => 0],
            ['iso' => 'SC','iso3'=>'SC','nicename'=> 'Seychelles','name' => 'Seychelles', 'available' => 0],
            ['iso' => 'SL','iso3'=>'SL','nicename'=> 'Sierra Leone','name' => 'Sierra Leone', 'available' => 0],
            ['iso' => 'SG','iso3'=>'SG','nicename'=> 'Singapore','name' => 'Singapore', 'available' => 0],
            ['iso' => 'SK','iso3'=>'SK','nicename'=> 'Slovakia','name' => 'Slovakia', 'available' => 0],
            ['iso' => 'SI','iso3'=>'SI','nicename'=> 'Slovenia','name' => 'Slovenia', 'available' => 0],
            ['iso' => 'SB','iso3'=>'SB','nicename'=> 'Solomon Islands','name' => 'Solomon Islands', 'available' => 0],
            ['iso' => 'SO','iso3'=>'SO','nicename'=> 'Somalia','name' => 'Somalia', 'available' => 0],
            ['iso' => 'ZA','iso3'=>'ZA','nicename'=> 'South Africa','name' => 'South Africa', 'available' => 0],
            ['iso' => 'GS','iso3'=>'GS','nicename'=> 'South Georgia South Sandwich Islands','name' => 'South Georgia South Sandwich Islands', 'available' => 0],
            ['iso' => 'ES','iso3'=>'ES','nicename'=> 'Spain','name' => 'Spain', 'available' => 0],
            ['iso' => 'LK','iso3'=>'LK','nicename'=> 'Sri Lanka','name' => 'Sri Lanka', 'available' => 0],
            ['iso' => 'SH','iso3'=>'SH','nicename'=> 'St. Helena','name' => 'St. Helena', 'available' => 0],
            ['iso' => 'PM','iso3'=>'PM','nicename'=> 'St. Pierre and Miquelon','name' => 'St. Pierre and Miquelon', 'available' => 0],
            ['iso' => 'SD','iso3'=>'SD','nicename'=> 'Sudan','name' => 'Sudan', 'available' => 0],
            ['iso' => 'SR','iso3'=>'SR','nicename'=> 'Suriname','name' => 'Suriname', 'available' => 0],
            ['iso' => 'SJ','iso3'=>'SJ','nicename'=> 'Svalbarn and Jan Mayen Islands','name' => 'Svalbarn and Jan Mayen Islands', 'available' => 0],
            ['iso' => 'SZ','iso3'=>'SZ','nicename'=> 'Swaziland','name' => 'Swaziland', 'available' => 0],
            ['iso' => 'SE','iso3'=>'SE','nicename'=> 'Sweden','name' => 'Sweden', 'available' => 0],
            ['iso' => 'CH','iso3'=>'CH','nicename'=> 'Switzerland','name' => 'Switzerland', 'available' => 0],
            ['iso' => 'SY','iso3'=>'SY','nicename'=> 'Syrian Arab Republic','name' => 'Syrian Arab Republic', 'available' => 0],
            ['iso' => 'TW','iso3'=>'TW','nicename'=> 'Taiwan','name' => 'Taiwan', 'available' => 0],
            ['iso' => 'TJ','iso3'=>'TJ','nicename'=> 'Tajikistan','name' => 'Tajikistan', 'available' => 0],
            ['iso' => 'TZ','iso3'=>'TZ','nicename'=> 'Tanzania, United Republic of','name' => 'Tanzania, United Republic of', 'available' => 0],
            ['iso' => 'TH','iso3'=>'TH','nicename'=> 'Thailand','name' => 'Thailand', 'available' => 0],
            ['iso' => 'TG','iso3'=>'TG','nicename'=> 'Togo','name' => 'Togo', 'available' => 0],
            ['iso' => 'TK','iso3'=>'TK','nicename'=> 'Tokelau','name' => 'Tokelau', 'available' => 0],
            ['iso' => 'TO','iso3'=>'TO','nicename'=> 'Tonga','name' => 'Tonga', 'available' => 0],
            ['iso' => 'TT','iso3'=>'TT','nicename'=> 'Trinidad and Tobago','name' => 'Trinidad and Tobago', 'available' => 0],
            ['iso' => 'TN','iso3'=>'TN','nicename'=> 'Tunisia','name' => 'Tunisia', 'available' => 0],
            ['iso' => 'TR','iso3'=>'TR','nicename'=> 'Turkey','name' => 'Turkey', 'available' => 0],
            ['iso' => 'TM','iso3'=>'TM','nicename'=> 'Turkmenistan','name' => 'Turkmenistan', 'available' => 0],
            ['iso' => 'TC','iso3'=>'TC','nicename'=> 'Turks and Caicos Islands','name' => 'Turks and Caicos Islands', 'available' => 0],
            ['iso' => 'TV','iso3'=>'TV','nicename'=> 'Tuvalu','name' => 'Tuvalu', 'available' => 0],
            ['iso' => 'UG','iso3'=>'UG','nicename'=> 'Uganda','name' => 'Uganda', 'available' => 0],
            ['iso' => 'UA','iso3'=>'UA','nicename'=> 'Ukraine','name' => 'Ukraine', 'available' => 0],
            ['iso' => 'AE','iso3'=>'AE','nicename'=> 'United Arab Emirates','name' => 'United Arab Emirates', 'available' => 0],
            ['iso' => 'GB','iso3'=>'GB','nicename'=> 'United Kingdom','name' => 'United Kingdom', 'available' => 0],
            ['iso' => 'UM','iso3'=>'UM','nicename'=> 'United States minor outlying islands','name' => 'United States minor outlying islands', 'available' => 0],
            ['iso' => 'UY','iso3'=>'UY','nicename'=> 'Uruguay','name' => 'Uruguay', 'available' => 0],
            ['iso' => 'UZ','iso3'=>'UZ','nicename'=> 'Uzbekistan','name' => 'Uzbekistan', 'available' => 0],
            ['iso' => 'VU','iso3'=>'VU','nicename'=> 'Vanuatu','name' => 'Vanuatu', 'available' => 0],
            ['iso' => 'VA','iso3'=>'VA','nicename'=> 'Vatican City State','name' => 'Vatican City State', 'available' => 0],
            ['iso' => 'VE','iso3'=>'VE','nicename'=> 'Venezuela','name' => 'Venezuela', 'available' => 0],
            ['iso' => 'VN','iso3'=>'VN','nicename'=> 'Vietnam','name' => 'Vietnam', 'available' => 0],
            ['iso' => 'VG','iso3'=>'VG','nicename'=> 'Virgin Islands (British)','name' => 'Virgin Islands (British)', 'available' => 0],
            ['iso' => 'VI','iso3'=>'VI','nicename'=> 'Virgin Islands (U.S.)','name' => 'Virgin Islands (U.S.)', 'available' => 0],
            ['iso' => 'WF','iso3'=>'WF','nicename'=> 'Wallis and Futuna Islands','name' => 'Wallis and Futuna Islands', 'available' => 0],
            ['iso' => 'EH','iso3'=>'EH','nicename'=> 'Western Sahara','name' => 'Western Sahara', 'available' => 0],
            ['iso' => 'YE','iso3'=>'YE','nicename'=> 'Yemen','name' => 'Yemen', 'available' => 0],
            ['iso' => 'YU','iso3'=>'YU','nicename'=> 'Yugoslavia','name' => 'Yugoslavia', 'available' => 0],
            ['iso' => 'ZR','iso3'=>'ZR','nicename'=> 'Zaire','name' => 'Zaire', 'available' => 0],
            ['iso' => 'ZM','iso3'=>'ZM','nicename'=> 'Zambia','name' => 'Zambia', 'available' => 0],
            ['iso' => 'ZW','iso3'=>'ZW','nicename'=> 'Zimbabwe','name' => 'Zimbabwe', 'available' => 0],
        ];
        collect($countries)->each(fn ($country) => Country::factory()->create($country));
        // DB::table('countries')->insert($countries);
    }
}
